[[constraint]]
  name = "github.com/akamai/AkamaiOPEN-edgegrid-golang"
  version = "0.7.4"

[[constraint]]
  branch = "master"
  name = "github.com/akamai/cli-common-golang"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true

